repositories:
  remote:
   - http://repo.fire.dse.vic.gov.au/content/groups/fisg
   - http://www.ibiblio.org/maven2
  release_to:
    url: http://repo.fire.dse.vic.gov.au/content/repositories/releases/
    username: upload

artifacts:
  javax_naming: geronimo:geronimo-naming:jar:1.1.1
